import { NextResponse } from 'next/server';
import { query } from '@/lib/db';
import { decodeQRCodeFromBuffer, parseStudentData } from '@/utils/qr-decoder';

export async function POST(request: Request) {
  try {
    const formData = await request.formData();
    const qrCodeFile = formData.get('qrCode');

    if (!qrCodeFile) {
      return NextResponse.json(
        { success: false, error: 'QR code file is required' },
        { status: 400 }
      );
    }

    console.log('📷 QR code received:', {
      name: (qrCodeFile as File).name,
      type: (qrCodeFile as File).type,
      size: (qrCodeFile as File).size
    });

    // Convert file to buffer
    const arrayBuffer = await (qrCodeFile as File).arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);

    let studentData;
    try {
      const qrContent = await decodeQRCodeFromBuffer(buffer);
      studentData = parseStudentData(qrContent);
      console.log('✅ Successfully decoded QR content:', studentData);
    } catch (decodeError: unknown) {
      console.error('❌ QR decoding failed:', decodeError);
      const message = decodeError instanceof Error ? decodeError.message : String(decodeError);

      return NextResponse.json(
        {
          success: false,
          error: 'Could not read QR code. Please upload a valid QR code.',
          debug: {
            error: message,
            suggestion: 'Make sure the QR code was generated by the school system'
          }
        },
        { status: 400 }
      );
    }

    const studentId = studentData.student_id;
    console.log('🎯 Extracted student_id from QR:', studentId);

    // Query the student/secretary from students table
    try {
      const users = await query(
        `SELECT id, student_id, student_name, grade, section, status, student_type
         FROM students
         WHERE student_id = ?`,
        [studentId]
      );

      if (users.length === 0) {
        return NextResponse.json(
          {
            success: false,
            error: `User with ID "${studentId}" not found`,
            debug: { qrData: studentData }
          },
          { status: 404 }
        );
      }

      const user = users[0];

      if (user.status.toLowerCase() !== 'active') {
        return NextResponse.json(
          {
            success: false,
            error: 'User account is inactive',
            debug: { userId: user.student_id, userName: user.student_name, status: user.status }
          },
          { status: 403 }
        );
      }

      console.log(`✅ QR login successful for ${user.student_type}:`, user.student_name);

      return NextResponse.json({
        success: true,
        data: {
          studentId: user.student_id,
          studentName: user.student_name,
          grade: user.grade,
          section: user.section,
          role: user.student_type // "student" or "secretary"
        },
        debug: {
          qrData: studentData,
          userStatus: user.status,
          decoded: true
        },
        message: 'QR login successful'
      });

    } catch (dbError: unknown) {
      console.error('❌ Database error:', dbError);
      const message = dbError instanceof Error ? dbError.message : String(dbError);
      return NextResponse.json(
        { success: false, error: 'Database error: ' + message },
        { status: 500 }
      );
    }

  } catch (error: unknown) {
    console.error('❌ QR login general error:', error);
    const message = error instanceof Error ? error.message : String(error);
    return NextResponse.json(
      { success: false, error: 'Failed to process QR code: ' + message },
      { status: 500 }
    );
  }
}
